/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface LogoToken {
        "src": string;
    }
    interface PageHome {
    }
    interface PageLoading {
    }
    interface ScrollPage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLLogoTokenElement extends Components.LogoToken, HTMLStencilElement {
    }
    var HTMLLogoTokenElement: {
        prototype: HTMLLogoTokenElement;
        new (): HTMLLogoTokenElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageLoadingElement extends Components.PageLoading, HTMLStencilElement {
    }
    var HTMLPageLoadingElement: {
        prototype: HTMLPageLoadingElement;
        new (): HTMLPageLoadingElement;
    };
    interface HTMLScrollPageElement extends Components.ScrollPage, HTMLStencilElement {
    }
    var HTMLScrollPageElement: {
        prototype: HTMLScrollPageElement;
        new (): HTMLScrollPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "logo-token": HTMLLogoTokenElement;
        "page-home": HTMLPageHomeElement;
        "page-loading": HTMLPageLoadingElement;
        "scroll-page": HTMLScrollPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface LogoToken {
        "src"?: string;
    }
    interface PageHome {
    }
    interface PageLoading {
    }
    interface ScrollPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "logo-token": LogoToken;
        "page-home": PageHome;
        "page-loading": PageLoading;
        "scroll-page": ScrollPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "logo-token": LocalJSX.LogoToken & JSXBase.HTMLAttributes<HTMLLogoTokenElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-loading": LocalJSX.PageLoading & JSXBase.HTMLAttributes<HTMLPageLoadingElement>;
            "scroll-page": LocalJSX.ScrollPage & JSXBase.HTMLAttributes<HTMLScrollPageElement>;
        }
    }
}
